[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/oca,/mnt/extra-addons/custom
admin_passwd = $pbkdf2-sha512$600000$D0EIgTDG.J.Tcu6911oLwQ$/Z/9adbIkSXkN1dj3zRz/T5l3s5c/mWFivKhC.//joi/UBaL.g6Z7rW2/8QxBIH0JJJII.ekhdze9FnLIYGmvA
http_port = 8069

